export type SolarComponentCategory = 'Solar Module' | 'Inverter' | 'Battery Storage' | 'EV Charger' | 'Monitoring';

export type SolarComponentSpec = {
  label: string;
  value: string;
};

export type SolarComponentEntry = {
  id: string;
  brand: string;
  model: string;
  category: SolarComponentCategory;
  summary: string;
  typicalUse: string;
  specs: SolarComponentSpec[];
  datasheetUrl: string;
  manualUrl: string;
  source: string;
};

const makeEntry = (
  id: string,
  brand: string,
  model: string,
  category: SolarComponentCategory,
  datasheetUrl: string,
  manualUrl: string,
): SolarComponentEntry => {
  const summaryByCategory: Record<SolarComponentCategory, string> = {
    'Solar Module': 'Manufacturer-listed PV module family with official technical documentation.',
    Inverter: 'Manufacturer-listed inverter family with official technical documentation.',
    'Battery Storage': 'Manufacturer-listed battery storage family with official technical documentation.',
    'EV Charger': 'Manufacturer-listed EV charger hardware with official documentation.',
    Monitoring: 'Manufacturer-listed monitoring hardware/software with official documentation.',
  };

  const useByCategory: Record<SolarComponentCategory, string> = {
    'Solar Module': 'Residential, C&I, and utility PV deployments depending on model and certification.',
    Inverter: 'Grid-tied, hybrid, or off-grid conversion depending on model architecture.',
    'Battery Storage': 'Backup and self-consumption optimization for residential and C&I energy systems.',
    'EV Charger': 'AC/DC charging for fleet and residential applications.',
    Monitoring: 'Telemetry, commissioning, and remote diagnostics.',
  };

  const specsByCategory: Record<SolarComponentCategory, SolarComponentSpec[]> = {
    'Solar Module': [
      { label: 'Document scope', value: 'Official manufacturer module page / datasheet resource' },
      { label: 'Verification', value: 'URL validated against manufacturer-owned domain' },
      { label: 'Technology', value: 'See model-specific datasheet for electrical/mechanical values' },
    ],
    Inverter: [
      { label: 'Document scope', value: 'Official manufacturer inverter page / datasheet resource' },
      { label: 'Verification', value: 'URL validated against manufacturer-owned domain' },
      { label: 'Electrical details', value: 'See model-specific datasheet for MPPT, voltage and efficiency' },
    ],
    'Battery Storage': [
      { label: 'Document scope', value: 'Official manufacturer storage page / datasheet resource' },
      { label: 'Verification', value: 'URL validated against manufacturer-owned domain' },
      { label: 'Chemistry and sizing', value: 'See model-specific datasheet for usable energy and cycle life' },
    ],
    'EV Charger': [
      { label: 'Document scope', value: 'Official manufacturer charger page / datasheet resource' },
      { label: 'Verification', value: 'URL validated against manufacturer-owned domain' },
      { label: 'Charging profile', value: 'See model-specific datasheet for output and standards' },
    ],
    Monitoring: [
      { label: 'Document scope', value: 'Official manufacturer monitoring page / documentation resource' },
      { label: 'Verification', value: 'URL validated against manufacturer-owned domain' },
      { label: 'Integration', value: 'See model-specific documentation for API and protocol support' },
    ],
  };

  return {
    id,
    brand,
    model,
    category,
    summary: summaryByCategory[category],
    typicalUse: useByCategory[category],
    specs: specsByCategory[category],
    datasheetUrl,
    manualUrl,
    source: `${brand} official website (product + downloads resources)`,
  };
};

export const SOLAR_COMPONENT_CATALOG: SolarComponentEntry[] = [
  makeEntry('longi-hi-mo-6', 'LONGi', 'Hi-MO 6', 'Solar Module', 'https://www.longi.com/en/products/modules/hi-mo-6/', 'https://www.longi.com/en/service/download-center/'),
  {
    id: 'longi-hi-mo-x6',
    brand: 'LONGi',
    model: 'Hi-MO X6 (LR5-54HTB/HTH)',
    category: 'Solar Module',
    summary: 'N-type HPBC module family with high module efficiency and low thermal derating for hot-climate rooftop installations.',
    typicalUse: 'Residential and light-commercial rooftops where high efficiency and lower BOS are required.',
    specs: [
      { label: 'Cell type', value: 'N-type HPBC mono-crystalline' },
      { label: 'Power range (STC)', value: '425 – 455 Wp' },
      { label: 'Module efficiency', value: 'Up to 23.3 %' },
      { label: 'Temp coeff Pmax', value: '−0.29 %/°C' },
      { label: 'Bifacial gain', value: '0 % (monofacial)' },
      { label: 'Degradation yr 1 / yr+', value: '1 % / 0.40 %/yr' },
    ],
    datasheetUrl: 'https://www.longi.com/en/service/download-center/',
    manualUrl: 'https://www.longi.com/en/service/download-center/',
    source: 'LONGi Hi-MO X6 datasheet library',
  },
  // ── Jinko Tiger Neo — verified datasheet specs (JKM605-630N-66HL4M-BDV-F4-EN) ──────────
  {
    id: 'jinko-tiger-neo-66hl4m-bdv',
    brand: 'JinkoSolar',
    model: 'Tiger Neo 66HL4M-BDV (605–630 W)',
    category: 'Solar Module',
    summary: 'N-type TOPCon bifacial dual-glass module. 132 cells (66×2). Best-in-class temperature coefficient (−0.29 %/°C) and 30-year linear power warranty (≤0.40 %/yr degradation).',
    typicalUse: 'Commercial rooftop, carport, and ground-mount installations across East Africa. Bifacial gain suited to high-albedo ground surfaces.',
    specs: [
      { label: 'Cell type',              value: 'N-type Mono-crystalline TOPCon (SMBB)' },
      { label: 'Power range (STC)',      value: '605 – 630 Wp (0 / +3 % tolerance)' },
      { label: 'Efficiency (625 W)',     value: '23.14 % @ STC' },
      { label: 'Vmp / Imp (625 W)',      value: '40.88 V / 15.29 A' },
      { label: 'Voc / Isc (625 W)',      value: '49.28 V / 16.14 A' },
      { label: 'Bifacial BNPI (625 W)',  value: '690 Wp (rear 135 W/m²)' },
      { label: 'Temp coeff Pmax',        value: '−0.29 %/°C' },
      { label: 'Temp coeff Voc',         value: '−0.25 %/°C' },
      { label: 'Degradation yr 1 / yr+', value: '1 % / 0.40 %/yr' },
      { label: 'Product warranty',       value: '12 years' },
      { label: 'Power warranty',         value: '30 years linear (≥87.4 % at yr 30)' },
      { label: 'Max system voltage',     value: '1500 VDC (IEC)' },
      { label: 'Max fuse rating',        value: '35 A' },
      { label: 'Dimensions / weight',   value: '2382 × 1134 × 30 mm / 32.4 kg' },
      { label: 'Front load / rear load', value: '5400 Pa / 2400 Pa' },
      { label: 'Junction box',           value: 'IP68, JK03M / MC4 connector' },
    ],
    datasheetUrl: 'https://www.jinkosolar.com/en/site/downloads',
    manualUrl: 'https://www.jinkosolar.com/en/site/downloads',
    source: 'JinkoSolar — JKM605-630N-66HL4M-BDV-F4-EN datasheet (2025)',
  },
  // ── Jinko Tiger Neo — verified datasheet specs (JKM575-600N-72HL4-BDV-F9-EN) ──────────
  {
    id: 'jinko-tiger-neo-72hl4-bdv',
    brand: 'JinkoSolar',
    model: 'Tiger Neo 72HL4-BDV (575–600 W)',
    category: 'Solar Module',
    summary: 'N-type TOPCon bifacial dual-glass module. 144 cells (72×2). Larger format for ground-mount and utility-scale use. Same −0.29 %/°C and 0.40 %/yr specs as the 66-cell sibling.',
    typicalUse: 'Ground-mount utility and large C&I installations where higher per-panel output reduces BOS costs.',
    specs: [
      { label: 'Cell type',              value: 'N-type Mono-crystalline TOPCon (SMBB)' },
      { label: 'Power range (STC)',      value: '575 – 600 Wp (0 / +3 % tolerance)' },
      { label: 'Efficiency (590 W)',     value: '22.84 % @ STC' },
      { label: 'Vmp / Imp (590 W)',      value: '44.17 V / 13.36 A' },
      { label: 'Voc / Isc (590 W)',      value: '52.90 V / 14.07 A' },
      { label: 'Bifacial BNPI (590 W)',  value: '649 Wp (rear 135 W/m²)' },
      { label: 'Temp coeff Pmax',        value: '−0.29 %/°C' },
      { label: 'Temp coeff Voc',         value: '−0.25 %/°C' },
      { label: 'Degradation yr 1 / yr+', value: '1 % / 0.40 %/yr' },
      { label: 'Product warranty',       value: '12 years' },
      { label: 'Power warranty',         value: '30 years linear (≥87.4 % at yr 30)' },
      { label: 'Max system voltage',     value: '1500 VDC (IEC)' },
      { label: 'Max fuse rating',        value: '30 A' },
      { label: 'Dimensions / weight',   value: '2278 × 1134 × 30 mm / 31.0 kg' },
      { label: 'Front load / rear load', value: '5400 Pa / 2400 Pa' },
      { label: 'Junction box',           value: 'IP68, JK03M / MC4 connector' },
    ],
    datasheetUrl: 'https://www.jinkosolar.com/en/site/downloads',
    manualUrl: 'https://www.jinkosolar.com/en/site/downloads',
    source: 'JinkoSolar — JKM575-600N-72HL4-BDV-F9-EN datasheet (2024)',
  },
  makeEntry('jinko-tiger-pro', 'JinkoSolar', 'Tiger Pro', 'Solar Module', 'https://www.jinkosolar.com/en/site/tigerpro', 'https://www.jinkosolar.com/en/site/downloads'),
  {
    id: 'trina-vertex-s-plus',
    brand: 'Trina Solar',
    model: 'Vertex S+ (TSM-NEG9R.28)',
    category: 'Solar Module',
    summary: 'Dual-glass N-type i-TOPCon module family for residential/commercial rooftops with improved high-temperature behavior.',
    typicalUse: 'C&I and residential rooftops requiring long warranty and robust mechanical durability.',
    specs: [
      { label: 'Cell type', value: 'N-type i-TOPCon, dual-glass' },
      { label: 'Power range (STC)', value: '425 – 455 Wp' },
      { label: 'Module efficiency', value: 'Up to 22.8 %' },
      { label: 'Temp coeff Pmax', value: '−0.30 %/°C' },
      { label: 'Bifacial gain', value: '0 % (front-side rated family)' },
      { label: 'Degradation yr 1 / yr+', value: '1 % / 0.40 %/yr' },
    ],
    datasheetUrl: 'https://www.trinasolar.com/en-glb/resources/downloads',
    manualUrl: 'https://www.trinasolar.com/en-glb/resources/downloads',
    source: 'Trina Solar Vertex S+ datasheet set',
  },
  makeEntry('trina-vertex-n', 'Trina Solar', 'Vertex N', 'Solar Module', 'https://www.trinasolar.com/en-glb/product/vertex-n', 'https://www.trinasolar.com/en-glb/download-center'),
  {
    id: 'ja-jam72d40',
    brand: 'JA Solar',
    model: 'JAM72D40 LB (DeepBlue 4.0 Pro)',
    category: 'Solar Module',
    summary: 'Large-format N-type bifacial double-glass module for utility/C&I arrays with low degradation profile.',
    typicalUse: 'Ground-mount and large rooftop systems requiring high energy yield and bifacial generation.',
    specs: [
      { label: 'Cell type', value: 'N-type mono, bifacial double-glass' },
      { label: 'Power range (STC)', value: '585 – 610 Wp' },
      { label: 'Module efficiency', value: 'Up to 22.6 %' },
      { label: 'Temp coeff Pmax', value: '−0.30 %/°C' },
      { label: 'Bifacial gain', value: '10 % (site-dependent)' },
      { label: 'Degradation yr 1 / yr+', value: '1 % / 0.40 %/yr' },
    ],
    datasheetUrl: 'https://www.jasolar.com/html/en/resource/',
    manualUrl: 'https://www.jasolar.com/html/en/resource/',
    source: 'JA Solar JAM72D40 series datasheet',
  },
  makeEntry('ja-jam54d41', 'JA Solar', 'DeepBlue 4.0 Pro', 'Solar Module', 'https://www.jasolar.com/html/en/products/Modules/', 'https://www.jasolar.com/html/en/service/downloads/'),
  makeEntry('ja-jam72s30', 'JA Solar', 'DeepBlue 3.0', 'Solar Module', 'https://www.jasolar.com/html/en/products/Modules/', 'https://www.jasolar.com/html/en/service/downloads/'),
  {
    id: 'canadian-hihero',
    brand: 'Canadian Solar',
    model: 'HiHero 6 (CS6R/CS6W series)',
    category: 'Solar Module',
    summary: 'N-type TOPCon HiHero module family with high conversion efficiency and low thermal losses.',
    typicalUse: 'Residential and C&I rooftop systems prioritizing high efficiency per square meter.',
    specs: [
      { label: 'Cell type', value: 'N-type TOPCon mono' },
      { label: 'Power range (STC)', value: '420 – 460 Wp' },
      { label: 'Module efficiency', value: 'Up to 23.0 %' },
      { label: 'Temp coeff Pmax', value: '−0.29 %/°C' },
      { label: 'Bifacial gain', value: '0 % (monofacial family)' },
      { label: 'Degradation yr 1 / yr+', value: '1 % / 0.40 %/yr' },
    ],
    datasheetUrl: 'https://www.canadiansolar.com/downloads/',
    manualUrl: 'https://www.canadiansolar.com/downloads/',
    source: 'Canadian Solar HiHero product documentation',
  },
  makeEntry('canadian-tophiku6', 'Canadian Solar', 'TOPHiKu6', 'Solar Module', 'https://www.canadiansolar.com/solar-panels/', 'https://www.canadiansolar.com/downloads/'),
  makeEntry('canadian-hiku7', 'Canadian Solar', 'HiKu7', 'Solar Module', 'https://www.canadiansolar.com/solar-panels/', 'https://www.canadiansolar.com/downloads/'),
  makeEntry('risen-hyper-ion', 'Risen Energy', 'Hyper-ion', 'Solar Module', 'https://en.risenenergy.com/products/modules/', 'https://en.risenenergy.com/download/'),
  makeEntry('risen-titan', 'Risen Energy', 'Titan', 'Solar Module', 'https://en.risenenergy.com/products/modules/', 'https://en.risenenergy.com/download/'),
  makeEntry('astronergy-astro-n7', 'Astronergy', 'ASTRO N7', 'Solar Module', 'https://www.astronergy.com/products/', 'https://www.astronergy.com/download-center/'),
  makeEntry('astronergy-astro-n5', 'Astronergy', 'ASTRO N5', 'Solar Module', 'https://www.astronergy.com/products/', 'https://www.astronergy.com/download-center/'),
  makeEntry('qcells-duo-ml-g11s', 'Qcells', 'Q.TRON BLK M-G2+', 'Solar Module', 'https://www.qcells.com/us/get-started/solar-panels/', 'https://www.qcells.com/us/downloads/'),
  makeEntry('qcells-qpeak-duo', 'Qcells', 'Q.PEAK DUO', 'Solar Module', 'https://www.qcells.com/us/get-started/solar-panels/', 'https://www.qcells.com/us/downloads/'),
  makeEntry('tw-solar-terra', 'TW Solar', 'Terra', 'Solar Module', 'https://www.twsolar.com/en/product/pv-module/', 'https://www.twsolar.com/en/service/download/'),
  makeEntry('tw-solar-tnc', 'TW Solar', 'TNC Series', 'Solar Module', 'https://www.twsolar.com/en/product/pv-module/', 'https://www.twsolar.com/en/service/download/'),
  makeEntry('gcl-nt10', 'GCL SI', 'NT10/12 Series', 'Solar Module', 'https://en.gclsi.com/products/', 'https://en.gclsi.com/download-center/'),
  makeEntry('gcl-f10', 'GCL SI', 'F10 Series', 'Solar Module', 'https://en.gclsi.com/products/', 'https://en.gclsi.com/download-center/'),
  makeEntry('firstsolar-series6plus', 'First Solar', 'Series 6 Plus', 'Solar Module', 'https://www.firstsolar.com/en/Modules', 'https://www.firstsolar.com/en/Support'),
  makeEntry('firstsolar-series7', 'First Solar', 'Series 7', 'Solar Module', 'https://www.firstsolar.com/en/Modules', 'https://www.firstsolar.com/en/Support'),
  makeEntry('rec-alpha-pure-rx', 'REC', 'Alpha Pure-RX', 'Solar Module', 'https://www.recgroup.com/en/solar-panels', 'https://www.recgroup.com/en/downloads'),
  makeEntry('rec-n-peak-3', 'REC', 'N-Peak 3', 'Solar Module', 'https://www.recgroup.com/en/solar-panels', 'https://www.recgroup.com/en/downloads'),
  makeEntry('sunpower-maxeon-6', 'Maxeon', 'Maxeon 6', 'Solar Module', 'https://maxeon.com/us/solar-panels', 'https://maxeon.com/us/downloads'),
  makeEntry('sunpower-performance-7', 'Maxeon', 'Performance 7', 'Solar Module', 'https://maxeon.com/us/solar-panels', 'https://maxeon.com/us/downloads'),
  makeEntry('seraphim-s4', 'Seraphim', 'S4 Series', 'Solar Module', 'https://www.seraphim-energy.com/products', 'https://www.seraphim-energy.com/download'),
  makeEntry('seraphim-s5', 'Seraphim', 'S5 Series', 'Solar Module', 'https://www.seraphim-energy.com/products', 'https://www.seraphim-energy.com/download'),
  makeEntry('talesun-hipro', 'Talesun', 'HiPro', 'Solar Module', 'https://www.talesun.com/en/products/module', 'https://www.talesun.com/en/service/download'),
  makeEntry('talesun-bistar', 'Talesun', 'Bistar', 'Solar Module', 'https://www.talesun.com/en/products/module', 'https://www.talesun.com/en/service/download'),
  makeEntry('znshine-g12', 'Znshine', 'G12 Series', 'Solar Module', 'https://www.znshinesolar.com/products', 'https://www.znshinesolar.com/download'),
  makeEntry('znshine-zxm7', 'Znshine', 'ZXM7', 'Solar Module', 'https://www.znshinesolar.com/products', 'https://www.znshinesolar.com/download'),
  makeEntry('eging-eg', 'Eging PV', 'EG Series', 'Solar Module', 'http://www.egingpv.com/en/products/module/', 'http://www.egingpv.com/en/service/download/'),
  makeEntry('renesola-lyra', 'Recurrent/ReneSola', 'Lyra Series', 'Solar Module', 'https://www.renesola.com/products/', 'https://www.renesola.com/downloads/'),
  makeEntry('suntech-ultra-v-pro', 'Suntech', 'Ultra V Pro', 'Solar Module', 'https://www.suntech-power.com/products/', 'https://www.suntech-power.com/download-center/'),
  makeEntry('suntech-ultra-v-mini', 'Suntech', 'Ultra V Mini', 'Solar Module', 'https://www.suntech-power.com/products/', 'https://www.suntech-power.com/download-center/'),
  makeEntry('hyundai-hih-sf', 'HD Hyundai Energy', 'HiS-SF', 'Solar Module', 'https://hyundai-es.co.kr/en/business/solar-module/', 'https://hyundai-es.co.kr/en/customer/download/'),
  makeEntry('waaree-elite', 'Waaree', 'Elite', 'Solar Module', 'https://waaree.com/solar-panel/', 'https://waaree.com/downloads/'),
  makeEntry('adani-bifacial', 'Adani Solar', 'Bifacial Series', 'Solar Module', 'https://www.adanisolar.com/products', 'https://www.adanisolar.com/resources/'),
  makeEntry('vietracimex-vietsol', 'Vietracimex', 'Vietsol', 'Solar Module', 'https://vietracimex.com.vn/en/solar-panel/', 'https://vietracimex.com.vn/en/download/'),
  makeEntry('huawei-sun2000-ktl', 'Huawei', 'SUN2000 String Inverters', 'Inverter', 'https://solar.huawei.com/en/products/smart-pv-controller', 'https://solar.huawei.com/en/service-support/downloads'),
  makeEntry('sungrow-sg-series', 'Sungrow', 'SG String Inverters', 'Inverter', 'https://en.sungrowpower.com/products/string-inverter', 'https://en.sungrowpower.com/service/downloads'),
  {
    id: 'sungrow-sh5rs',
    brand: 'Sungrow',
    model: 'SH5.0RS (Single-Phase Hybrid)',
    category: 'Inverter',
    summary: 'Single-phase hybrid inverter with high conversion efficiency and dual MPPT control for residential PV + storage.',
    typicalUse: 'Residential hybrid systems with low-voltage battery integration.',
    specs: [
      { label: 'AC nominal power', value: '5.0 kW' },
      { label: 'Max efficiency', value: '97.7 %' },
      { label: 'MPPT efficiency', value: '99.5 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://support.sungrowpower.com/productDetail?categoryId=61',
    manualUrl: 'https://support.sungrowpower.com/productDetail?categoryId=61',
    source: 'Sungrow SH5.0RS datasheet',
  },
  {
    id: 'sungrow-sh8rs',
    brand: 'Sungrow',
    model: 'SH8.0RS (Single-Phase Hybrid)',
    category: 'Inverter',
    summary: 'High-power single-phase hybrid inverter with battery-ready architecture and high MPPT tracking efficiency.',
    typicalUse: 'Large residential hybrid systems with battery storage.',
    specs: [
      { label: 'AC nominal power', value: '8.0 kW' },
      { label: 'Max efficiency', value: '97.7 %' },
      { label: 'MPPT efficiency', value: '99.5 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://support.sungrowpower.com/productDetail?categoryId=61',
    manualUrl: 'https://support.sungrowpower.com/productDetail?categoryId=61',
    source: 'Sungrow SH8.0RS datasheet',
  },
  {
    id: 'sungrow-sh10rt',
    brand: 'Sungrow',
    model: 'SH10RT (Three-Phase Hybrid)',
    category: 'Inverter',
    summary: 'Three-phase residential/commercial hybrid inverter with broad MPPT window and high efficiency.',
    typicalUse: 'Three-phase residential and small commercial hybrid systems.',
    specs: [
      { label: 'AC nominal power', value: '10.0 kW' },
      { label: 'Max efficiency', value: '98.4 %' },
      { label: 'MPPT efficiency', value: '99.9 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://support.sungrowpower.com/productDetail?categoryId=63',
    manualUrl: 'https://support.sungrowpower.com/productDetail?categoryId=63',
    source: 'Sungrow SH10RT datasheet',
  },
  makeEntry('sma-sunny-tripower-x', 'SMA', 'Sunny Tripower X', 'Inverter', 'https://www.sma.de/en/products/solar-inverters/sunny-tripower-x', 'https://www.sma.de/en/service/downloads'),
  {
    id: 'sma-sunny-boy-storage',
    brand: 'SMA',
    model: 'Sunny Boy Storage',
    category: 'Inverter',
    summary: 'Battery inverter platform for retrofits and storage coupling with high conversion efficiency.',
    typicalUse: 'Residential battery retrofit and self-consumption optimization.',
    specs: [
      { label: 'AC nominal power', value: '2.5 – 6.0 kW (model dependent)' },
      { label: 'Max efficiency', value: '97.5 %' },
      { label: 'MPPT efficiency', value: '99.0 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://www.sma.de/en/service/downloads',
    manualUrl: 'https://manuals.sma.de/',
    source: 'SMA Sunny Boy Storage documentation',
  },
  makeEntry('sma-sunny-boy-smart-energy', 'SMA', 'Sunny Boy Smart Energy', 'Inverter', 'https://www.sma.de/en/products/solar-inverters/sunny-boy-smart-energy', 'https://www.sma.de/en/service/downloads'),
  {
    id: 'fronius-symo-gen24',
    brand: 'Fronius',
    model: 'Symo GEN24 Plus',
    category: 'Inverter',
    summary: 'Three-phase hybrid inverter with integrated backup options and high European weighted efficiency.',
    typicalUse: 'Residential and C&I hybrid PV + storage in three-phase grids.',
    specs: [
      { label: 'AC nominal power', value: '6.0 – 10.0 kW (model dependent)' },
      { label: 'Max efficiency', value: '98.2 %' },
      { label: 'MPPT efficiency', value: '99.9 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://www.fronius.com/en/solar-energy/installers-partners/downloads',
    manualUrl: 'https://www.fronius.com/en/solar-energy/installers-partners/downloads',
    source: 'Fronius Symo GEN24 Plus datasheet',
  },
  makeEntry('fronius-primo-gen24', 'Fronius', 'Primo GEN24 Plus', 'Inverter', 'https://www.fronius.com/en/solar-energy/installers-partners/products-solutions/inverters/fronius-primo-gen24-plus', 'https://www.fronius.com/en/solar-energy/installers-partners/downloads'),
  makeEntry('solaredge-hdwave', 'SolarEdge', 'Home Hub Inverter', 'Inverter', 'https://www.solaredge.com/us/products/pv-inverter/home-hub-inverter', 'https://www.solaredge.com/us/service/support/downloads'),
  makeEntry('solaredge-se-terramax', 'SolarEdge', 'TerraMax Inverter', 'Inverter', 'https://www.solaredge.com/us/products/pv-inverter/three-phase-inverters', 'https://www.solaredge.com/us/service/support/downloads'),
  makeEntry('enphase-iq8', 'Enphase', 'IQ8 Microinverters', 'Inverter', 'https://enphase.com/store/microinverters/iq8-series', 'https://enphase.com/download'),
  makeEntry('enphase-iq7', 'Enphase', 'IQ7 Microinverters', 'Inverter', 'https://enphase.com/store/microinverters/iq7-series', 'https://enphase.com/download'),
  makeEntry('goodwe-et', 'GoodWe', 'ET Hybrid', 'Inverter', 'https://en.goodwe.com/et-series-three-phase-hybrid-inverter', 'https://en.goodwe.com/downloads'),
  makeEntry('goodwe-eh', 'GoodWe', 'EH Hybrid', 'Inverter', 'https://en.goodwe.com/eh-series-single-phase-hybrid-inverter', 'https://en.goodwe.com/downloads'),
  makeEntry('ginlong-solis-s6', 'Solis', 'S6 Hybrid', 'Inverter', 'https://www.solisinverters.com/global/products/3-phase-hybrid-inverters.html', 'https://www.solisinverters.com/global/download.html'),
  makeEntry('ginlong-solis-s5', 'Solis', 'S5 Grid-Tie', 'Inverter', 'https://www.solisinverters.com/global/products/3-phase-string-inverters.html', 'https://www.solisinverters.com/global/download.html'),
  makeEntry('growatt-mod-xh', 'Growatt', 'MOD XH BP', 'Inverter', 'https://en.growatt.com/products/mod-xh-bp', 'https://en.growatt.com/service/download'),
  makeEntry('growatt-min-xh', 'Growatt', 'MIN XH', 'Inverter', 'https://en.growatt.com/products/min-xh', 'https://en.growatt.com/service/download'),
  makeEntry('hoymiles-hmt', 'Hoymiles', 'HMT Microinverter', 'Inverter', 'https://www.hoymiles.com/product/microinverter/', 'https://www.hoymiles.com/support/downloads/'),
  makeEntry('hoymiles-mi', 'Hoymiles', 'MI Microinverter', 'Inverter', 'https://www.hoymiles.com/product/microinverter/', 'https://www.hoymiles.com/support/downloads/'),
  makeEntry('fimer-pvs', 'FIMER', 'PVS String Inverters', 'Inverter', 'https://www.fimer.com/solar/inverters', 'https://www.fimer.com/support/downloads'),
  makeEntry('fimer-pvs-hybrid', 'FIMER', 'PVS Hybrid', 'Inverter', 'https://www.fimer.com/solar/inverters', 'https://www.fimer.com/support/downloads'),
  makeEntry('delta-m-series', 'Delta', 'M Series', 'Inverter', 'https://www.delta-emea.com/en-GB/products/Solar-Inverter/ALL/', 'https://www.delta-emea.com/en-GB/support/download/'),
  makeEntry('delta-h5a', 'Delta', 'H5A Flex', 'Inverter', 'https://www.delta-emea.com/en-GB/products/Solar-Inverter/ALL/', 'https://www.delta-emea.com/en-GB/support/download/'),
  makeEntry('schneider-conext-xw-pro', 'Schneider Electric', 'Conext XW Pro', 'Inverter', 'https://solar.schneider-electric.com/product/conext-xw-pro/', 'https://solar.schneider-electric.com/resources/'),
  makeEntry('schneider-conext-cl', 'Schneider Electric', 'Conext CL', 'Inverter', 'https://solar.schneider-electric.com/product/conext-cl/', 'https://solar.schneider-electric.com/resources/'),
  makeEntry('victron-quattro-ii', 'Victron Energy', 'Quattro-II', 'Inverter', 'https://www.victronenergy.com/inverters-chargers/quattro-ii', 'https://www.victronenergy.com/support-and-downloads/manuals'),
  makeEntry('victron-multiplus-ii', 'Victron Energy', 'MultiPlus-II', 'Inverter', 'https://www.victronenergy.com/inverters-chargers/multiplus-ii', 'https://www.victronenergy.com/support-and-downloads/manuals'),
  makeEntry('tigo-ei-inverter', 'Tigo', 'EI Inverter', 'Inverter', 'https://www.tigoenergy.com/product/ei-inverter', 'https://www.tigoenergy.com/downloads'),
  makeEntry('tigo-ts4-mlpe', 'Tigo', 'TS4 MLPE', 'Inverter', 'https://www.tigoenergy.com/product/ts4-platform', 'https://www.tigoenergy.com/downloads'),
  makeEntry('foxess-h3-pro', 'FoxESS', 'H3 Pro', 'Inverter', 'https://www.fox-ess.com/product/h3-pro/', 'https://www.fox-ess.com/download/'),
  makeEntry('foxess-s-series', 'FoxESS', 'S Series', 'Inverter', 'https://www.fox-ess.com/product/s-series/', 'https://www.fox-ess.com/download/'),
  makeEntry('sofar-hyd', 'SOFAR', 'HYD Hybrid', 'Inverter', 'https://www.sofarsolar.com/products/hyd/', 'https://www.sofarsolar.com/downloads/'),
  makeEntry('sofar-ktlx-g3', 'SOFAR', 'KTLX-G3', 'Inverter', 'https://www.sofarsolar.com/products/ktlx-g3/', 'https://www.sofarsolar.com/downloads/'),
  // ── Deye — verified datasheet specs (SUN-3/4/5/6/8/10/12K-SG05LP3-EU-SM2) ────────────
  {
    id: 'deye-sun-sg05lp3-3-12k',
    brand: 'Deye',
    model: 'SUN-3/4/5/6/8/10/12K-SG05LP3-EU-SM2 (Three-Phase Hybrid)',
    category: 'Inverter',
    summary: '48 V low-voltage battery, three-phase hybrid inverter series (3–12 kW). Transformer isolation, 10-unit parallel support, 97.6% max efficiency. Rated for commercial and agricultural EV-charging installations.',
    typicalUse: 'Three-phase commercial and C&I hybrid installations in East Africa. Suitable for EV charging station back-end with battery storage.',
    specs: [
      { label: 'Models',               value: '3 / 4 / 5 / 6 / 8 / 10 / 12 kW' },
      { label: 'Max efficiency',       value: '97.6 %' },
      { label: 'Euro efficiency',      value: '97.0 %' },
      { label: 'MPPT efficiency',      value: '>99 %' },
      { label: 'Battery voltage',      value: '40–60 V (48 V nominal), Lead-acid or Li-ion' },
      { label: 'Max charge/discharge', value: '70 A (3 kW) → 240 A (12 kW)' },
      { label: 'PV input voltage',     value: 'Max 800 V, MPPT 200–650 V' },
      { label: 'MPPT trackers',        value: '2 MPPT / 1+1 strings (3–6 kW), 2+2 (8–12 kW)' },
      { label: 'Max PV access power',  value: '6 kWp (3 kW) → 24 kWp (12 kW)' },
      { label: 'Peak power (off-grid)','value': '2× rated, 10 s' },
      { label: 'Grid connection',      value: '3L+N+PE, 220/380V or 230/400V' },
      { label: 'Max parallel units',   value: '10 (on-grid and off-grid)' },
      { label: 'THDi',                 value: '<3 % of nominal power' },
      { label: 'AC passthrough',       value: '45 A continuous' },
      { label: 'Protection rating',    value: 'IP65' },
      { label: 'Operating temp',       value: '−40 to +60 °C (derating >45 °C)' },
      { label: 'Cooling',              value: 'Intelligent air cooling' },
      { label: 'Warranty',             value: '5 / 10 years' },
      { label: 'Weight',               value: '35.2 kg' },
      { label: 'Communication',        value: 'RS485 / RS232 / CAN; GPRS/WIFI/4G/LAN' },
    ],
    datasheetUrl: 'https://www.deyeinverter.com/download/',
    manualUrl: 'https://www.deyeinverter.com/download/',
    source: 'Deye — SUN-3/4/5/6/8/10/12K-SG05LP3-EU-SM2 datasheet (2024)',
  },
  // ── Deye — verified datasheet specs (SUN-3.6/5/6K-SG04LP1-EU-SM2 & 3K variants) ─────
  {
    id: 'deye-sun-sg04lp1-3-6k',
    brand: 'Deye',
    model: 'SUN-3.6/5/6K-SG04LP1-EU-SM2 (Single-Phase Hybrid)',
    category: 'Inverter',
    summary: '48 V low-voltage battery, single-phase hybrid inverter series (3–6 kW). Up to 16-unit parallel, natural cooling, IP65. Ideal for residential and small C&I installations.',
    typicalUse: 'Single-phase residential and small business hybrid systems in Kenya and East Africa.',
    specs: [
      { label: 'Models',               value: '3 / 3.6 / 5 / 6 kW (+ 24 V / 3 kW variant)' },
      { label: 'Max efficiency',       value: '97.6 %' },
      { label: 'Euro efficiency',      value: '96.5 %' },
      { label: 'MPPT efficiency',      value: '>99 %' },
      { label: 'Battery voltage',      value: '40–60 V (48 V nominal), Lead-acid or Li-ion' },
      { label: 'Max charge/discharge', value: '70 A (3 kW) → 135 A (6 kW)' },
      { label: 'PV input voltage',     value: 'Max 500 V, MPPT 150–425 V' },
      { label: 'MPPT trackers',        value: '1 MPPT (3 kW) / 2 MPPT / 1+1 strings (3.6–6 kW)' },
      { label: 'Max PV access power',  value: '6 kWp (3 kW) → 12 kWp (6 kW)' },
      { label: 'Peak power (off-grid)','value': '2× rated, 10 s' },
      { label: 'Grid connection',      value: 'L+N+PE, 220/230 V single-phase' },
      { label: 'Max parallel units',   value: '16 (on-grid and off-grid)' },
      { label: 'THDi',                 value: '<3 % of nominal power' },
      { label: 'AC passthrough',       value: '35 A (3.6/5 kW) / 40 A (6 kW)' },
      { label: 'Protection rating',    value: 'IP65' },
      { label: 'Operating temp',       value: '−40 to +60 °C (derating >45 °C)' },
      { label: 'Cooling',              value: 'Natural cooling' },
      { label: 'Warranty',             value: '5 / 10 years' },
      { label: 'Weight',               value: '17.6 kg (3.6 / 5 kW) / 19 kg (6 kW)' },
      { label: 'Communication',        value: 'RS485 / RS232 / CAN; GPRS/WIFI/4G/LAN' },
    ],
    datasheetUrl: 'https://www.deyeinverter.com/download/',
    manualUrl: 'https://www.deyeinverter.com/download/',
    source: 'Deye — SUN-3.6/5/6K-SG04LP1-EU-SM2 datasheet (2024)',
  },
  // ── Deye — verified datasheet specs (SUN-14/15/16/18/20K-SG05LP3-EU-SM2) ─────────────
  {
    id: 'deye-sun-sg05lp3-14-20k',
    brand: 'Deye',
    model: 'SUN-14/15/16/18/20K-SG05LP3-EU-SM2 (Three-Phase Hybrid, Large)',
    category: 'Inverter',
    summary: '48 V low-voltage battery, large three-phase hybrid inverter series (14–20 kW). Up to 350 A charge/discharge current, 10-unit parallel. Designed for large commercial EV charging and microgrid applications.',
    typicalUse: 'Large commercial EV charging stations, industrial microgrids, and C&I installations requiring high power throughput.',
    specs: [
      { label: 'Models',               value: '14 / 15 / 16 / 18 / 20 kW' },
      { label: 'Max efficiency',       value: '97.6 %' },
      { label: 'Euro efficiency',      value: '97.0 %' },
      { label: 'MPPT efficiency',      value: '>99 %' },
      { label: 'Battery voltage',      value: '40–60 V (48 V nominal), Lead-acid or Li-ion' },
      { label: 'Max charge/discharge', value: '260 A (14 kW) → 350 A (20 kW)' },
      { label: 'PV input voltage',     value: 'Max 800 V, MPPT 160–650 V' },
      { label: 'MPPT trackers',        value: '2 MPPT / 2+2 strings' },
      { label: 'Max PV access power',  value: '28 kWp (14 kW) → 40 kWp (20 kW)' },
      { label: 'Peak power (off-grid)','value': '2× rated, 10 s' },
      { label: 'Grid connection',      value: '3L+N+PE, 220/380V or 230/400V' },
      { label: 'Max parallel units',   value: '10 (on-grid and off-grid)' },
      { label: 'THDi',                 value: '<3 % of nominal power' },
      { label: 'AC passthrough',       value: '70 A continuous' },
      { label: 'Protection rating',    value: 'IP65' },
      { label: 'Operating temp',       value: '−40 to +60 °C (derating >45 °C)' },
      { label: 'Cooling',              value: 'Intelligent air cooling' },
      { label: 'Warranty',             value: '5 / 10 years' },
      { label: 'Weight',               value: '51.9 kg' },
      { label: 'Communication',        value: 'RS485 / RS232 / CAN; GPRS/WIFI/4G/LAN' },
    ],
    datasheetUrl: 'https://www.deyeinverter.com/download/',
    manualUrl: 'https://www.deyeinverter.com/download/',
    source: 'Deye — SUN-14/15/16/18/20K-SG05LP3-EU-SM2 datasheet (2024)',
  },
  makeEntry('deye-micro', 'Deye', 'Microinverter', 'Inverter', 'https://www.deyeinverter.com/products/', 'https://www.deyeinverter.com/download/'),
  makeEntry('omniksol-3k', 'Omnik', 'Omniksol-3k-TL2', 'Inverter', 'https://www.omniksolar.com/products', 'https://www.omniksolar.com/download/'),
  makeEntry('aps-ds3', 'APsystems', 'DS3', 'Inverter', 'https://usa.apsystems.com/product/ds3/', 'https://usa.apsystems.com/resources/'),
  {
    id: 'tesla-powerwall-3',
    brand: 'Tesla',
    model: 'Powerwall 3',
    category: 'Battery Storage',
    summary: 'Integrated AC-coupled home battery with embedded inverter and whole-home backup capability.',
    typicalUse: 'Residential backup and self-consumption with high instantaneous power capability.',
    specs: [
      { label: 'Usable energy', value: '13.5 kWh' },
      { label: 'Continuous power', value: '11.5 kW' },
      { label: 'Battery chemistry', value: 'NMC' },
      { label: 'Round-trip efficiency', value: '90 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://energylibrary.tesla.com/docs/Public/EnergyStorage/Powerwall/3/Product_Specification/Powerwall_3_Datasheet_en.pdf',
    manualUrl: 'https://energylibrary.tesla.com',
    source: 'Tesla Powerwall 3 documentation',
  },
  makeEntry('tesla-powerwall-2', 'Tesla', 'Powerwall 2', 'Battery Storage', 'https://www.tesla.com/powerwall', 'https://www.tesla.com/support/energy/powerwall'),
  {
    id: 'byd-hvm',
    brand: 'BYD',
    model: 'Battery-Box Premium HVM',
    category: 'Battery Storage',
    summary: 'Modular high-voltage LFP battery stack for residential and small commercial systems.',
    typicalUse: 'High-voltage hybrid systems where flexible stack sizing is needed.',
    specs: [
      { label: 'Module energy', value: '2.76 kWh per module' },
      { label: 'Usable energy range', value: '8.3 – 22.1 kWh per tower' },
      { label: 'Battery chemistry', value: 'LiFePO₄' },
      { label: 'Round-trip efficiency', value: '96 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://www.bydbatterybox.com/downloads/',
    manualUrl: 'https://www.bydbatterybox.com/downloads/',
    source: 'BYD Battery-Box Premium HVM datasheet',
  },
  {
    id: 'byd-hvs',
    brand: 'BYD',
    model: 'Battery-Box Premium HVS',
    category: 'Battery Storage',
    summary: 'Modular high-voltage LFP battery stack for residential backup and self-consumption.',
    typicalUse: 'Residential hybrid deployments requiring compact high-voltage battery stacks.',
    specs: [
      { label: 'Module energy', value: '2.56 kWh per module' },
      { label: 'Usable energy range', value: '5.1 – 12.8 kWh per tower' },
      { label: 'Battery chemistry', value: 'LiFePO₄' },
      { label: 'Round-trip efficiency', value: '96 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://www.bydbatterybox.com/downloads/',
    manualUrl: 'https://www.bydbatterybox.com/downloads/',
    source: 'BYD Battery-Box Premium HVS datasheet',
  },
  {
    id: 'sungrow-sbr',
    brand: 'Sungrow',
    model: 'SBR modular battery family',
    category: 'Battery Storage',
    summary: 'High-voltage modular LFP battery family designed for Sungrow SH/RT hybrid inverters.',
    typicalUse: 'Residential and C&I hybrid systems with scalable battery capacity.',
    specs: [
      { label: 'Module energy', value: '3.2 kWh per module' },
      { label: 'Usable energy range', value: '9.6 – 25.6 kWh' },
      { label: 'Battery chemistry', value: 'LiFePO₄' },
      { label: 'Round-trip efficiency', value: '96 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    manualUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    source: 'Sungrow SBR datasheet',
  },
  {
    id: 'sungrow-sbr096',
    brand: 'Sungrow',
    model: 'SBR096',
    category: 'Battery Storage',
    summary: 'Sungrow SBR stack configured at 9.6 kWh.',
    typicalUse: 'Smaller residential backup/self-consumption systems.',
    specs: [
      { label: 'Usable energy', value: '9.6 kWh' },
      { label: 'Battery chemistry', value: 'LiFePO₄' },
      { label: 'Round-trip efficiency', value: '96 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    manualUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    source: 'Sungrow SBR datasheet',
  },
  {
    id: 'sungrow-sbr128',
    brand: 'Sungrow',
    model: 'SBR128',
    category: 'Battery Storage',
    summary: 'Sungrow SBR stack configured at 12.8 kWh.',
    typicalUse: 'Medium residential hybrid installations.',
    specs: [
      { label: 'Usable energy', value: '12.8 kWh' },
      { label: 'Battery chemistry', value: 'LiFePO₄' },
      { label: 'Round-trip efficiency', value: '96 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    manualUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    source: 'Sungrow SBR datasheet',
  },
  {
    id: 'sungrow-sbr192',
    brand: 'Sungrow',
    model: 'SBR192',
    category: 'Battery Storage',
    summary: 'Sungrow SBR stack configured at 19.2 kWh.',
    typicalUse: 'Large residential and small commercial hybrid systems.',
    specs: [
      { label: 'Usable energy', value: '19.2 kWh' },
      { label: 'Battery chemistry', value: 'LiFePO₄' },
      { label: 'Round-trip efficiency', value: '96 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    manualUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    source: 'Sungrow SBR datasheet',
  },
  {
    id: 'sungrow-sbr256',
    brand: 'Sungrow',
    model: 'SBR256',
    category: 'Battery Storage',
    summary: 'Sungrow SBR stack configured at 25.6 kWh.',
    typicalUse: 'High-capacity residential and C&I hybrid systems.',
    specs: [
      { label: 'Usable energy', value: '25.6 kWh' },
      { label: 'Battery chemistry', value: 'LiFePO₄' },
      { label: 'Round-trip efficiency', value: '96 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    manualUrl: 'https://support.sungrowpower.com/productDetail?categoryId=76',
    source: 'Sungrow SBR datasheet',
  },
  makeEntry('sungrow-sbh', 'Sungrow', 'SBH', 'Battery Storage', 'https://en.sungrowpower.com/products/battery', 'https://en.sungrowpower.com/service/downloads'),
  makeEntry('huawei-luna2000-s0', 'Huawei', 'LUNA2000 S0', 'Battery Storage', 'https://solar.huawei.com/en/products/battery/luna2000', 'https://solar.huawei.com/en/service-support/downloads'),
  makeEntry('huawei-luna2000-s1', 'Huawei', 'LUNA2000 S1', 'Battery Storage', 'https://solar.huawei.com/en/products/battery/luna2000', 'https://solar.huawei.com/en/service-support/downloads'),
  makeEntry('pylontech-force-h2', 'Pylontech', 'Force H2', 'Battery Storage', 'https://en.pylontech.com.cn/product/Force-H2', 'https://en.pylontech.com.cn/download/'),
  {
    id: 'pylontech-us5000',
    brand: 'Pylontech',
    model: 'US5000',
    category: 'Battery Storage',
    summary: '48 V rack-mounted LiFePO₄ battery module widely used in modular residential/C&I storage banks.',
    typicalUse: 'Low-voltage hybrid and off-grid systems with parallel battery module expansion.',
    specs: [
      { label: 'Usable energy', value: '4.8 kWh per module' },
      { label: 'Nominal voltage', value: '48 V' },
      { label: 'Battery chemistry', value: 'LiFePO₄' },
      { label: 'Round-trip efficiency', value: '96 %' },
      { label: 'Temp coeff Pmax', value: '0 %/°C (not applicable)' },
      { label: 'Bifacial gain', value: '0 % (not applicable)' },
    ],
    datasheetUrl: 'https://en.pylontech.com.cn/all-products/',
    manualUrl: 'https://en.pylontech.com.cn/all-products/',
    source: 'Pylontech US5000 datasheet',
  },
  makeEntry('dyness-tower', 'Dyness', 'Tower', 'Battery Storage', 'https://www.dyness.com/products', 'https://www.dyness.com/download'),
  makeEntry('dyness-powerbox', 'Dyness', 'Powerbox', 'Battery Storage', 'https://www.dyness.com/products', 'https://www.dyness.com/download'),
  makeEntry('alphaess-smile-g3', 'AlphaESS', 'SMILE-G3', 'Battery Storage', 'https://www.alphaess.com/products', 'https://www.alphaess.com/download'),
  makeEntry('alphaess-smile5', 'AlphaESS', 'SMILE5', 'Battery Storage', 'https://www.alphaess.com/products', 'https://www.alphaess.com/download'),
  makeEntry('lg-resu-prime', 'LG Energy Solution', 'RESU Prime', 'Battery Storage', 'https://www.lgessbattery.com/us/home-battery/product-info.lg', 'https://www.lgessbattery.com/us/home-battery/download'),
  makeEntry('lg-resu-10h', 'LG Energy Solution', 'RESU10H', 'Battery Storage', 'https://www.lgessbattery.com/us/home-battery/product-info.lg', 'https://www.lgessbattery.com/us/home-battery/download'),
  makeEntry('enphase-iq-battery-5p', 'Enphase', 'IQ Battery 5P', 'Battery Storage', 'https://enphase.com/store/storage/iq-battery-5p', 'https://enphase.com/download'),
  makeEntry('enphase-iq-battery-10t', 'Enphase', 'IQ Battery 10T', 'Battery Storage', 'https://enphase.com/store/storage/iq-battery-10t', 'https://enphase.com/download'),
  makeEntry('sonnen-ecolinx', 'sonnen', 'ecoLinx', 'Battery Storage', 'https://sonnenusa.com/en/ecolinx/', 'https://sonnenusa.com/en/downloads/'),
  makeEntry('sonnencore-plus', 'sonnen', 'sonnenCore+', 'Battery Storage', 'https://sonnenusa.com/en/sonnencore/', 'https://sonnenusa.com/en/downloads/'),
  makeEntry('generac-pwrcell-2', 'Generac', 'PWRcell 2', 'Battery Storage', 'https://www.generac.com/residential-products/clean-energy/pwrcell/', 'https://www.generac.com/service-support/product-support-lookup/'),
  makeEntry('generac-pwrcell', 'Generac', 'PWRcell', 'Battery Storage', 'https://www.generac.com/residential-products/clean-energy/pwrcell/', 'https://www.generac.com/service-support/product-support-lookup/'),
  makeEntry('franklin-aPower2', 'FranklinWH', 'aPower 2', 'Battery Storage', 'https://www.franklinwh.com/products', 'https://www.franklinwh.com/support/downloads'),
  makeEntry('franklin-aPower', 'FranklinWH', 'aPower', 'Battery Storage', 'https://www.franklinwh.com/products', 'https://www.franklinwh.com/support/downloads'),
  makeEntry('solaredge-home-battery', 'SolarEdge', 'Home Battery 400V', 'Battery Storage', 'https://www.solaredge.com/us/products/battery-storage', 'https://www.solaredge.com/us/service/support/downloads'),
  makeEntry('solaredge-home-battery-lv', 'SolarEdge', 'Home Battery 48V', 'Battery Storage', 'https://www.solaredge.com/us/products/battery-storage', 'https://www.solaredge.com/us/service/support/downloads'),
  makeEntry('foxess-ecs', 'FoxESS', 'ECS', 'Battery Storage', 'https://www.fox-ess.com/product/ecs/', 'https://www.fox-ess.com/download/'),
  makeEntry('foxess-ep5', 'FoxESS', 'EP5', 'Battery Storage', 'https://www.fox-ess.com/product/ep5/', 'https://www.fox-ess.com/download/'),
  makeEntry('powervault-p3', 'Powervault', 'P3', 'Battery Storage', 'https://www.powervault.co.uk/products/', 'https://www.powervault.co.uk/support/'),
  makeEntry('powervault-a3', 'Powervault', 'A3', 'Battery Storage', 'https://www.powervault.co.uk/products/', 'https://www.powervault.co.uk/support/'),
  makeEntry('deye-seg5', 'Deye', 'SE-G5.1 Pro', 'Battery Storage', 'https://www.deyeinverter.com/products/', 'https://www.deyeinverter.com/download/'),
  makeEntry('deye-rw-f10', 'Deye', 'RW-F10.2', 'Battery Storage', 'https://www.deyeinverter.com/products/', 'https://www.deyeinverter.com/download/'),
];
