/**
 * @canonical src/components/layout/DashboardSidebar.tsx
 *
 * This file is intentionally a re-export shim.
 * The single source of truth for DashboardSidebar lives in:
 *   src/components/layout/DashboardSidebar.tsx
 *
 * All future edits should be made there — do NOT edit this file directly.
 */
export {
  DashboardSidebar,
  type DashboardSection,
  type SidebarContextMetric,
} from '@/components/layout/DashboardSidebar';
