-- SafariCharge initial PostgreSQL migration
-- Generated by Prisma Migrate

CREATE TABLE "User" (
    "id"        TEXT NOT NULL,
    "email"     TEXT NOT NULL,
    "name"      TEXT,
    "role"      TEXT NOT NULL DEFAULT 'viewer',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_createdAt_idx" ON "User"("createdAt");
CREATE INDEX "User_role_idx" ON "User"("role");

CREATE TABLE "LiveReading" (
    "id"        TEXT NOT NULL,
    "siteId"    TEXT NOT NULL,
    "source"    TEXT NOT NULL,
    "metric"    TEXT NOT NULL,
    "value"     DOUBLE PRECISION NOT NULL,
    "unit"      TEXT NOT NULL DEFAULT '',
    "quality"   TEXT NOT NULL DEFAULT 'good',
    "ts"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LiveReading_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "LiveReading_siteId_metric_ts_idx" ON "LiveReading"("siteId", "metric", "ts");
CREATE INDEX "LiveReading_ts_idx" ON "LiveReading"("ts");

CREATE TABLE "Scenario" (
    "id"          TEXT NOT NULL,
    "name"        TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "config"      JSONB NOT NULL,
    "results"     JSONB,
    "createdBy"   TEXT NOT NULL DEFAULT '',
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"   TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Scenario_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Scenario_createdAt_idx" ON "Scenario"("createdAt");
CREATE INDEX "Scenario_createdBy_idx" ON "Scenario"("createdBy");

CREATE TABLE "AlertRule" (
    "id"        TEXT NOT NULL,
    "siteId"    TEXT NOT NULL,
    "metric"    TEXT NOT NULL,
    "operator"  TEXT NOT NULL,
    "threshold" DOUBLE PRECISION NOT NULL,
    "severity"  TEXT NOT NULL DEFAULT 'warning',
    "enabled"   BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "AlertRule_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "AlertRule_siteId_metric_idx" ON "AlertRule"("siteId", "metric");
