name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  typecheck:
    name: Type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npx prisma generate
        env:
          DATABASE_URL: 'file:./dev.db'
      - run: npx tsc --noEmit

  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npx prisma generate
        env:
          DATABASE_URL: 'file:./dev.db'
      - run: npx eslint . --max-warnings=9999

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [typecheck]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npx prisma generate
        env:
          DATABASE_URL: 'file:./dev.db'
      - name: Next.js build
        run: npx next build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          DATABASE_URL: 'file:./dev.db'
